describe('Secret Menu with Cypress Studio', () => {
  beforeEach(() => {
    cy.visit('/secret-menu');
  });

  // run this test and click a magic wand aside test

  it('does stuff generated by Cypress Studio', () => {
    /* ==== Generated with Cypress Studio ==== */
    cy.get('#minimum-rating-visibility').click();
    cy.get('#restaurant-visibility-filter').select('KFC');
    cy.get('[for="show-name"]').click();
    cy.get('#show-name').uncheck();
    cy.get('#show-whereToOrder').uncheck();
    cy.get('[for="show-ingredients"]').click();
    cy.get('#show-ingredients').uncheck();
    cy.get('[for="show-secret"]').click();
    cy.get('#show-secret').uncheck();
    cy.get('[for="show-howToOrder"]').click();
    cy.get('#show-howToOrder').uncheck();
    cy.get('[for="show-description"]').click();
    cy.get('#show-description').uncheck();
    cy.get('[for="show-popularity"]').click();
    cy.get('#show-popularity').uncheck();
    cy.get('#show-howToOrder').check();
    /* ==== End Cypress Studio ==== */
  });
});
