version: '3.8'

services:
  auth-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    depends_on:
      - postgres
    environment:
      PORT: 3010
      POSTGRES_HOST: host.docker.internal
    ports:
      - 3010:3010

  postgres:
    container_name: postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
    image: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: