version: '3.8'

services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-api:
    container_name: auth-api
    build: .
    ports:
      - 3030:3030
volumes:
  pgdata: