version: '3.8'

services:
  backend:
    build: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3030:3030
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: