version: '3.8'

services:
  backend:
    restart: always
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    command: mongod --quiet --logpath /dev/null

  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}